In [14]:
import pandas as pd
import json
import ast

In [5]:
df_carriers = pd.read_json(r"C:\duan\DE\E-Commerce Supply Chain Analytics Lakehouse\data\raw\carriers.json")
df_carriers.head()

  carrier_id                carrier_name    code contact_phone service_type
0    CAR_001  Giao Hàng Tiết Kiệm (GHTK)    GHTK     1900 6092     Standard
1    CAR_002       Giao Hàng Nhanh (GHN)     GHN   1900 636677      Express
2    CAR_003                Viettel Post     VTP     1900 8095     Standard
3    CAR_004                VNPost / EMS  VNPOST   1900 545415      Economy
4    CAR_005                   Ninja Van   NINJA   1900 886877      Express

In [6]:
df_carriers.shape

(5, 5)

In [8]:
df_carriers.dtypes

carrier_id       str
carrier_name     str
code             str
contact_phone    str
service_type     str
dtype: object

In [9]:
df_orders = pd.read_json(r"C:\duan\DE\E-Commerce Supply Chain Analytics Lakehouse\data\raw\orders.json")
df_orders.head()

,order_id,customer,warehouse_id,order_date,total_items,total_amount,payment_method
0,ORD-20261007-001,"{'name': 'Nhật Xuân Dương', 'phone': '(02) 875...",WH_DAD,2026-10-30 18:14:58,1,709000,COD
1,ORD-20261007-002,"{'name': 'Nhật Quang Trần', 'phone': '08 5718 ...",WH_DAD,2026-10-23 12:07:58,5,175000,BANK_TRANSFER
2,ORD-20261007-003,"{'name': 'Cô Hồng Nguyễn', 'phone': '(07)821-0...",WH_SGN,2026-10-19 15:09:58,4,3331000,BANK_TRANSFER
3,ORD-20261007-004,"{'name': 'Hồng Vũ', 'phone': '04 5377 4632', '...",WH_HAN,2026-10-12 18:39:58,1,866000,COD
4,ORD-20261007-005,"{'name': 'Chị Mai Trần', 'phone': '08 4129 653...",WH_SGN,2026-11-05 08:59:58,2,1180000,MOMO

In [16]:
df_orders['customer'].iloc[0]

{'name': 'Nhật Xuân Dương',
 'phone': '(02) 8753 3939',
 'address': '796 Hoàng Dãy, Huyện JaneQuận, 192410',
 'city': 'Hà Nội'}

In [17]:
customer_df = pd.json_normalize(df_orders['customer'])

In [18]:
customer_df.head()

,name,phone,address,city
0,Nhật Xuân Dương,(02) 8753 3939,"796 Hoàng Dãy, Huyện JaneQuận, 192410",Hà Nội
1,Nhật Quang Trần,08 5718 2310,"6 Jane Số, Quận JanePhường, 346344",Đà Nẵng
2,Cô Hồng Nguyễn,(07)821-0868,"23 Jane Làng, JohnThành phố, 380070",Đồng Nai
3,Hồng Vũ,04 5377 4632,"55 Jane Hẻm, Huyện JaneHuyện, 788410",Đồng Nai
4,Chị Mai Trần,08 4129 6535,"190 John Khu, Thị xã JaneThị xã, 564069",Bình Dương

In [20]:
df_orders = df_orders.drop(columns=['customer']).join(customer_df)

In [22]:
df_orders.head()

,order_id,warehouse_id,order_date,total_items,total_amount,payment_method,name,phone,address,city
0,ORD-20261007-001,WH_DAD,2026-10-30 18:14:58,1,709000,COD,Nhật Xuân Dương,(02) 8753 3939,"796 Hoàng Dãy, Huyện JaneQuận, 192410",Hà Nội
1,ORD-20261007-002,WH_DAD,2026-10-23 12:07:58,5,175000,BANK_TRANSFER,Nhật Quang Trần,08 5718 2310,"6 Jane Số, Quận JanePhường, 346344",Đà Nẵng
2,ORD-20261007-003,WH_SGN,2026-10-19 15:09:58,4,3331000,BANK_TRANSFER,Cô Hồng Nguyễn,(07)821-0868,"23 Jane Làng, JohnThành phố, 380070",Đồng Nai
3,ORD-20261007-004,WH_HAN,2026-10-12 18:39:58,1,866000,COD,Hồng Vũ,04 5377 4632,"55 Jane Hẻm, Huyện JaneHuyện, 788410",Đồng Nai
4,ORD-20261007-005,WH_SGN,2026-11-05 08:59:58,2,1180000,MOMO,Chị Mai Trần,08 4129 6535,"190 John Khu, Thị xã JaneThị xã, 564069",Bình Dương

In [24]:
df_orders.shape

(100, 10)

In [25]:
df_orders.dtypes

order_id            str
warehouse_id        str
order_date          str
total_items       int64
total_amount      int64
payment_method      str
name                str
phone               str
address             str
city                str
dtype: object

In [26]:
df_orders.describe()

       total_items  total_amount
count   100.000000  1.000000e+02
mean      2.750000  1.870330e+06
std       1.445124  9.336668e+05
min       1.000000  1.750000e+05
25%       1.000000  1.073750e+06
50%       3.000000  1.755000e+06
75%       4.000000  2.675500e+06
max       5.000000  3.484000e+06

In [27]:
df_orders.isnull().sum()

order_id          0
warehouse_id      0
order_date        0
total_items       0
total_amount      0
payment_method    0
name              0
phone             0
address           0
city              0
dtype: int64

In [28]:
df_orders.duplicated().sum()

np.int64(0)

In [29]:
df_orders['city'].unique()

<StringArray>
[         'Hà Nội',         'Đà Nẵng',        'Đồng Nai',      'Bình Dương',
         'Cần Thơ', 'TP. Hồ Chí Minh',       'Hải Phòng']
Length: 7, dtype: str

In [30]:
df_orders.nunique()

order_id          100
warehouse_id        3
order_date         99
total_items         5
total_amount      100
payment_method      4
name               99
phone             100
address           100
city                7
dtype: int64

In [31]:
df_orders['payment_method'].unique()

<StringArray>
['COD', 'BANK_TRANSFER', 'MOMO', 'CREDIT_CARD']
Length: 4, dtype: str

In [32]:
df_orders['order_date'] = pd.to_datetime(df_orders['order_date'])
df_orders['order_date']= df_orders['order_date'].dt.normalize()

In [34]:
df_orders['total_amount'] = pd.to_numeric(df_orders['total_amount']).astype('Float64')

In [41]:
df_shipments = pd.read_json(r"C:\duan\DE\E-Commerce Supply Chain Analytics Lakehouse\data\raw\shipments.json")
df_shipments.head()

,shipment_id,order_id,carrier_id,tracking_number,shipping_fee,status,pickup_date,estimated_delivery_date,actual_delivery_date,delay_reason
0,SHIP-202609001,ORD-20261007-001,CAR_003,VTP61611378,37000,DELIVERED,2026-10-31 03:14:58,2026-11-03,2026-11-03 08:14:58,NaN
1,SHIP-202609002,ORD-20261007-002,CAR_005,NINJA47950897,21000,DELAYED,2026-10-23 14:07:58,2026-10-27,NaN,Phương tiện hư hỏng
2,SHIP-202609003,ORD-20261007-003,CAR_003,VTP98109173,25000,DELIVERED,2026-10-19 21:09:58,2026-10-23,2026-10-23 08:09:58,NaN
3,SHIP-202609004,ORD-20261007-004,CAR_002,GHN50654846,21000,DELAYED,2026-10-12 21:39:58,2026-10-14,NaN,Kho quá tải
4,SHIP-202609005,ORD-20261007-005,CAR_003,VTP89814433,42000,CANCELLED,2026-11-05 18:59:58,2026-11-09,NaN,Khách hàng hủy đơn

In [42]:
df_shipments.shape

(100, 10)

In [43]:
df_shipments.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   shipment_id              100 non-null    str
 1   order_id                 100 non-null    str
 2   carrier_id               100 non-null    str
 3   tracking_number          100 non-null    str
 4   shipping_fee             100 non-null    int64
 5   status                   100 non-null    str
 6   pickup_date              100 non-null    str
 7   estimated_delivery_date  100 non-null    str
 8   actual_delivery_date     44 non-null     str
 9   delay_reason             34 non-null     str
dtypes: int64(1), str(9)
memory usage: 7.9 KB

In [44]:
df_shipments.dtypes

shipment_id                  str
order_id                     str
carrier_id                   str
tracking_number              str
shipping_fee               int64
status                       str
pickup_date                  str
estimated_delivery_date      str
actual_delivery_date         str
delay_reason                 str
dtype: object

In [45]:
df_shipments.isnull().sum()

shipment_id                 0
order_id                    0
carrier_id                  0
tracking_number             0
shipping_fee                0
status                      0
pickup_date                 0
estimated_delivery_date     0
actual_delivery_date       56
delay_reason               66
dtype: int64

In [46]:
df_shipments.duplicated().sum()

np.int64(0)

In [47]:
df_shipments['delay_reason'] = df_shipments['delay_reason'].fillna('N/A')

In [48]:
df_shipments['pickup_date'] = pd.to_datetime(df_shipments['pickup_date'])
df_shipments['estimated_delivery_date'] = pd.to_datetime(df_shipments['estimated_delivery_date'])
df_shipments['actual_delivery_date'] = pd.to_datetime(df_shipments['actual_delivery_date'])